id = "uon"
name = "UON"
version = "0.1.0"
schema_version = 1
authors = ["УОН разработчики"]
description = "Поддержка УОН (Универсальная Объектная Нотация) для Zed"
repository = "https://github.com/MiCkEyZzZ/uon-zed"
